# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fff38f4b8277e445d5cc884209c8a55f92c9ab433e258abbdd6864238f83eafe71a506ffdd5fd91e38def6ef7d0c3241eebcf52cb039ed0aa4cfd689844b1ad

test:
  secret_key_base: 51ae475a2ebb3424f5babac7641ae4e79647fd5bfce5dafa1044501638be794a6239c8cdb54e6613b1eee79843b5c639527425004db810eecb23359eb40b7e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
